# Generated by Django 3.1.7 on 2021-05-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigodebarras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('barcodeimg', models.ImageField(blank=True, upload_to='codigodebarras/', verbose_name='imagenbarras')),
            ],
        ),
    ]
