# Generated by Django 3.1.7 on 2021-05-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBARRAS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigodebarras',
            name='country_id',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='codigodebarras',
            name='manufacturer_id',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='codigodebarras',
            name='product_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
