# Generated by Django 3.1.7 on 2021-04-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('cantidadP', models.IntegerField()),
                ('precioP', models.FloatField()),
                ('marcaP', models.CharField(blank=True, max_length=25, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventario de Productos',
                'ordering': ['id'],
            },
        ),
    ]
