# Generated by Django 3.1.7 on 2021-04-30 01:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas Registradas',
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=14, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=50, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores Registrados',
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('barcode', models.CharField(max_length=12, unique=True, verbose_name='Código de barras')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('num_venta', models.PositiveIntegerField(default=0, verbose_name='Número de ventas')),
                ('tipo', models.CharField(choices=[('0', 'CALZADO'), ('1', 'ROPA')], max_length=1, verbose_name='Tipo de producto')),
                ('almacen', models.CharField(choices=[('0', 'ALMACEN 1'), ('1', 'ALMACEN 2'), ('2', 'ALMACEN 3')], max_length=1, verbose_name='Almacén')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Existencias')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio de compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio de venta')),
                ('descripcion', models.CharField(blank=True, max_length=50, verbose_name='Descripción')),
                ('talla', models.CharField(blank=True, choices=[('0', 'EXTRA CHICA'), ('1', 'CHICA'), ('2', 'MEDIANA'), ('3', 'GRANDE'), ('4', 'EXTRA GRANDE'), ('2', 'SLIM')], max_length=1, verbose_name='Talla')),
                ('medida', models.CharField(blank=True, choices=[('0', '21'), ('1', '21.5'), ('2', '22'), ('3', '22.5'), ('4', '23'), ('5', '23.5'), ('6', '24'), ('7', '24.5'), ('8', '25'), ('9', '25.5'), ('10', '26'), ('11', '26.5'), ('12', '27'), ('13', '27.5'), ('14', '28'), ('15', '28.5'), ('16', '29'), ('17', '29.5'), ('18', '30')], max_length=2, verbose_name='Medida')),
                ('anular', models.BooleanField(default=False, verbose_name='Anular Producto')),
                ('img', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.marca')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Inventario de Productos',
                'db_table': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
