# Generated by Django 3.1.7 on 2021-05-28 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas Registradas',
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=14, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=50, verbose_name='Dirección')),
                ('clabe', models.CharField(blank=True, max_length=18, verbose_name='Clabe interbancaria')),
                ('nombre_banco', models.CharField(blank=True, max_length=40, verbose_name='Nombre de banco')),
                ('nombre_benefactor', models.CharField(blank=True, max_length=50, verbose_name='Nombre del beneficiario')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores Registrados',
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('barcode', models.CharField(blank=True, max_length=13, unique=True, verbose_name='Código de barras')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('10', 'CALZADO'), ('20', 'ROPA')], max_length=2, verbose_name='Tipo de producto')),
                ('almacen', models.CharField(choices=[('10', 'ALMACEN 1'), ('20', 'ALMACEN 2'), ('30', 'ALMACEN 3')], max_length=2, verbose_name='Almacén')),
                ('talla', models.CharField(blank=True, choices=[('', '---------'), ('00', 'CH'), ('01', 'M'), ('02', 'G'), ('', '---------'), ('03', '16'), ('04', '18'), ('05', '28'), ('06', '30'), ('07', '32'), ('08', '34'), ('09', '36'), ('10', '38'), ('11', '40'), ('12', '42'), ('13', '44')], max_length=2, verbose_name='Talla')),
                ('medida', models.CharField(blank=True, choices=[('', '---------'), ('00', '21'), ('01', '22'), ('02', '23'), ('03', '24'), ('04', '25'), ('05', '26'), ('06', '27'), ('07', '28'), ('08', '29'), ('09', '30'), ('', '---------'), ('10', '21.5'), ('11', '22.5'), ('12', '23.5'), ('13', '24.5'), ('14', '25.5'), ('15', '26.5'), ('16', '27.5'), ('17', '28.5'), ('18', '29.5')], max_length=2, verbose_name='Medida')),
                ('linea', models.CharField(blank=True, choices=[('00', 'ADULTO'), ('01', 'NIÑO')], max_length=2, verbose_name='Departamento')),
                ('color', models.CharField(blank=True, choices=[('00', 'ROJO'), ('01', 'AZUL'), ('02', 'AMARILLO'), ('03', 'NEGRO'), ('04', 'MORADO'), ('05', 'VERDE'), ('06', 'BLANCO')], max_length=2, verbose_name='Color')),
                ('modelo', models.CharField(blank=True, max_length=3, verbose_name='Modelo')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Existencias')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio de compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio de venta')),
                ('num_venta', models.PositiveIntegerField(default=0, verbose_name='Número de ventas')),
                ('anular', models.BooleanField(default=False, verbose_name='Anular Producto')),
                ('img', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.marca')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Inventario de Productos',
                'db_table': 'Productos',
                'ordering': ['-id'],
            },
        ),
    ]
