# Generated by Django 3.1.7 on 2021-07-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='promocion',
            field=models.CharField(blank=True, choices=[('0', '10%')], max_length=2, verbose_name='Promociones'),
        ),
    ]
