# Generated by Django 3.1.7 on 2021-04-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidadP',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombreP',
            field=models.CharField(max_length=50, verbose_name='Nombre de producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioP',
            field=models.FloatField(verbose_name='Precio'),
        ),
    ]
