# Generated by Django 3.1.7 on 2021-07-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_productos_promocion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='linea',
        ),
        migrations.AddField(
            model_name='productos',
            name='linea_c',
            field=models.CharField(blank=True, choices=[('00', 'BOTA'), ('01', 'BOTÍN'), ('02', 'CHOCLO'), ('03', 'ESCOLAR'), ('04', 'FLATS'), ('05', 'PANTUFLA'), ('06', 'SANDALIA'), ('07', 'ZAPATILLA'), ('08', 'PANTUFLA')], max_length=2, verbose_name='Línea de calzado'),
        ),
        migrations.AddField(
            model_name='productos',
            name='linea_r',
            field=models.CharField(blank=True, choices=[('', '---------'), ('00', 'BABERO'), ('01', 'PANTALON')], max_length=2, verbose_name='Línea de ropa'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='almacen',
            field=models.CharField(choices=[('1000', 'ALMACEN 1'), ('2000', 'ALMACEN 2'), ('3000', 'ALMACEN 3')], max_length=4, verbose_name='Almacén'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='modelo',
            field=models.CharField(blank=True, max_length=15, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='promocion',
            field=models.CharField(blank=True, choices=[('', '---------'), ('0', 'Sin promoción'), ('', '---------'), ('1', '10 %'), ('2', '20 %'), ('3', '30 %'), ('', '---------'), ('4', '2 x 1'), ('5', '3 x 2'), ('', '---------'), ('6', '1=10%, 2=20%')], max_length=2, verbose_name='Promociones'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='talla',
            field=models.CharField(blank=True, choices=[('', '---------'), ('00', 'XCH'), ('01', 'CH'), ('02', 'M'), ('03', 'G'), ('04', 'XG'), ('', '---------'), ('', 'DAMA'), ('05', '0'), ('06', '3'), ('07', '5'), ('08', '7'), ('09', '11'), ('10', '13'), ('11', '15'), ('', '---------'), ('', 'CABALLERO'), ('12', '28'), ('13', '30'), ('14', '32'), ('15', '34'), ('16', '36'), ('17', '38'), ('18', '40'), ('', '---------'), ('', 'NIÑO/A'), ('', 'Pendiente')], max_length=2, verbose_name='Talla'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(choices=[('100', 'CALZADO'), ('200', 'ROPA'), ('300', 'ACCESORIOS')], max_length=3, verbose_name='Tipo de producto'),
        ),
    ]
