# Generated by Django 3.1.7 on 2021-05-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_auto_20210501_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='clabe',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_banco',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nombre de bacno'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_benefactor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre del beneficiario'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='medida',
            field=models.CharField(blank=True, choices=[('0', '2'), ('1', '21/2'), ('2', '3'), ('3', '3 1/2'), ('', '---------'), ('4', 'CH'), ('5', 'M'), ('6', 'G'), ('', '---------'), ('7', 'CHICA'), ('8', 'MEDIANA'), ('9', 'GRANDE'), ('', '---------'), ('10', '22 MX'), ('11', '22.5 MX'), ('12', '23 MX')], max_length=2, verbose_name='Medida'),
        ),
    ]
