# Generated by Django 3.1.7 on 2021-04-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_auto_20210405_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidadP',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioP',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
    ]
