# Generated by Django 3.1.7 on 2021-05-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_auto_20210503_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='clabe',
            field=models.CharField(blank=True, max_length=18, verbose_name='Clabe interbancaria'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_banco',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nombre de banco'),
        ),
    ]
