# Generated by Django 3.1.7 on 2021-07-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_auto_20210707_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='genero',
            field=models.CharField(blank=True, choices=[('', '---------'), ('1', 'CABALLERO'), ('2', 'DAMA'), ('3', 'JOVEN'), ('4', 'NIÑO/A')], max_length=1, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='medida',
            field=models.CharField(blank=True, choices=[('', '---------'), ('', 'CABALLERO'), ('00', '25'), ('01', '26'), ('02', '27'), ('03', '28'), ('04', '29'), ('05', '30'), ('06', '31'), ('', '---------'), ('', 'DAMA'), ('07', '22'), ('08', '23'), ('09', '24'), ('10', '25'), ('11', '26'), ('12', '27'), ('', '---------'), ('', 'JOVEN'), ('13', '22'), ('14', '23'), ('15', '24'), ('16', '25'), ('17', '26'), ('', '---------'), ('', 'NIÑO/A'), ('18', '9'), ('19', '9.5'), ('20', '10'), ('21', '10.5'), ('22', '11'), ('23', '11.5'), ('24', '12'), ('25', '12.5'), ('26', '13'), ('27', '13.5'), ('28', '14'), ('29', '14.5'), ('30', '15'), ('31', '15.5'), ('32', '16'), ('33', '16.5'), ('34', '17'), ('35', '17.5'), ('36', '18'), ('37', '18.5'), ('38', '19'), ('39', '19.5'), ('40', '20'), ('41', '20.5'), ('42', '21'), ('43', '21.5')], max_length=2, verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='talla',
            field=models.CharField(blank=True, choices=[('', '---------'), ('00', 'XCH'), ('01', 'CH'), ('02', 'M'), ('03', 'G'), ('04', 'XG'), ('', '---------'), ('', 'DAMA'), ('05', '0'), ('06', '3'), ('07', '5'), ('08', '7'), ('09', '11'), ('10', '13'), ('11', '15'), ('', '---------'), ('', 'CABALLERO'), ('12', '28'), ('13', '30'), ('14', '32'), ('15', '34'), ('16', '36'), ('17', '38'), ('18', '40'), ('', '---------'), ('', 'NIÑO/A'), ('', 'Pendiente ...')], max_length=2, verbose_name='Talla'),
        ),
    ]
