# Generated by Django 3.1.7 on 2021-04-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_auto_20210405_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidadP',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioP',
            field=models.FloatField(verbose_name='Precio'),
        ),
    ]
