# Generated by Django 3.1.7 on 2021-07-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_auto_20210707_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='linea_c',
            field=models.CharField(blank=True, choices=[('', '---------'), ('00', 'BOTA'), ('01', 'BOTÍN'), ('02', 'CHOCLO'), ('03', 'ESCOLAR'), ('04', 'FLATS'), ('05', 'PANTUFLA'), ('06', 'SANDALIA'), ('07', 'ZAPATILLA'), ('08', 'PANTUFLA')], max_length=2, verbose_name='Línea de calzado'),
        ),
    ]
