# Generated by Django 3.1.7 on 2021-05-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_auto_20210504_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='depto',
            field=models.CharField(blank=True, choices=[('0', 'ADULTO'), ('1', 'NIÑO')], max_length=1, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='medida',
            field=models.CharField(blank=True, choices=[('', '---------'), ('5', '21'), ('6', '22'), ('7', '23'), ('8', '24'), ('9', '25'), ('10', '26'), ('11', '27'), ('12', '28'), ('13', '29'), ('14', '30'), ('', '---------'), ('15', '21.5'), ('16', '22.5'), ('17', '23.5'), ('18', '24.5'), ('19', '25.5'), ('20', '26.5'), ('21', '27.5'), ('21', '28.5'), ('21', '29.5')], max_length=2, verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='talla',
            field=models.CharField(blank=True, choices=[('0', 'CH'), ('1', 'M'), ('2', 'G')], max_length=1, verbose_name='Talla'),
        ),
    ]
