# Generated by Django 3.1.7 on 2021-05-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_auto_20210505_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='medida',
            field=models.CharField(blank=True, choices=[('', '---------'), ('0', '21'), ('1', '22'), ('2', '23'), ('3', '24'), ('4', '25'), ('5', '26'), ('6', '27'), ('7', '28'), ('8', '29'), ('9', '30'), ('', '---------'), ('10', '21.5'), ('11', '22.5'), ('12', '23.5'), ('13', '24.5'), ('14', '25.5'), ('15', '26.5'), ('16', '27.5'), ('17', '28.5'), ('18', '29.5')], max_length=2, verbose_name='Medida'),
        ),
    ]
