# Generated by Django 3.1.7 on 2021-07-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_auto_20210707_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='linea_c',
            field=models.CharField(blank=True, choices=[('', '---------'), ('00', 'BOTA'), ('01', 'BOTÍN'), ('02', 'CHOCLO'), ('03', 'ESCOLAR'), ('04', 'FLATS'), ('05', 'PANTUFLA'), ('06', 'SANDALIA'), ('07', 'TENIS'), ('08', 'ZAPATILLA')], max_length=2, verbose_name='Línea de calzado'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='promocion',
            field=models.CharField(blank=True, choices=[('', '---------'), ('0', 'Sin promoción'), ('', ''), ('1', '10 %'), ('2', '20 %'), ('3', '30 %'), ('', ''), ('4', '2 x 1'), ('5', '3 x 2'), ('', ''), ('6', '1=10%, 2=20%')], max_length=2, verbose_name='Promociones'),
        ),
    ]
