# Generated by Django 3.1.7 on 2021-04-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_productos_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='imagen',
            new_name='imagenP',
        ),
    ]
