# Generated by Django 3.1.7 on 2021-04-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_auto_20210407_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='modeloP',
            field=models.CharField(blank=True, max_length=30, verbose_name='Modelo'),
        ),
    ]
