# Generated by Django 3.1.7 on 2021-05-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_auto_20210505_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='color',
            field=models.CharField(blank=True, max_length=25, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='productos',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Modelo'),
        ),
    ]
