# Generated by Django 3.1.7 on 2021-07-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_auto_20210708_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='linea_a',
            field=models.CharField(blank=True, choices=[('', '---------'), ('00', 'LIMPIEZA'), ('01', 'MOCHILA')], max_length=2, verbose_name='Línea de accesorios'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='promocion',
            field=models.CharField(blank=True, choices=[('', '---------'), ('0', 'Sin promoción'), ('', ''), ('1', '10 %'), ('2', '20 %'), ('3', '30 %'), ('', ''), ('4', '2 x 1'), ('5', '3 x 2'), ('', ''), ('6', '1=10%, 2=20%'), ('', ''), ('7', '2 Adidas y obtén 10%')], max_length=2, verbose_name='Promociones'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='talla',
            field=models.CharField(blank=True, choices=[('', '---------'), ('00', 'XCH'), ('01', 'CH'), ('02', 'M'), ('03', 'G'), ('04', 'XG'), ('', '---------'), ('', 'CABALLERO'), ('12', '28'), ('13', '30'), ('14', '32'), ('15', '34'), ('16', '36'), ('17', '38'), ('18', '40'), ('', '---------'), ('', 'DAMA'), ('05', '0'), ('06', '3'), ('07', '5'), ('08', '7'), ('09', '11'), ('10', '13'), ('11', '15'), ('', '---------'), ('', 'NIÑO/A'), ('', 'Pendiente ...')], max_length=2, verbose_name='Talla'),
        ),
    ]
