# Generated by Django 3.1.7 on 2021-05-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0007_auto_20210505_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='depto',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='productos',
            name='linea',
            field=models.CharField(blank=True, choices=[('0', 'ADULTO'), ('1', 'NIÑO'), ('2', 'CABALLERO'), ('3', 'DAMA')], max_length=1, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='color',
            field=models.CharField(blank=True, choices=[('0', 'ROJO'), ('1', 'AZUL'), ('2', 'AMARILLO'), ('3', 'NEGRO'), ('4', 'MORADO'), ('5', 'VERDE'), ('6', 'BLANCO')], max_length=2, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='modelo',
            field=models.CharField(blank=True, max_length=6, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio de compra'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio de venta'),
        ),
    ]
