# Generated by Django 3.1.7 on 2021-08-23 20:24

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0007_auto_20210714_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('barcode', models.CharField(max_length=13, verbose_name='Código de barras')),
                ('stock_nuevo', models.IntegerField(default=0, verbose_name='Cantidad de productos ingresados')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y hora de actualización')),
                ('total_costo', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Costo total de productos ingresados')),
            ],
            options={
                'verbose_name': 'Movimientos',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'Movimientos',
                'ordering': ['-id'],
            },
        ),
    ]
