# Generated by Django 3.1.7 on 2021-05-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_auto_20210505_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='barcodeimg',
            field=models.ImageField(blank=True, upload_to='codigodebarras/', verbose_name='imagenbarras'),
        ),
    ]
