# Generated by Django 3.1.7 on 2021-08-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_movimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='genero',
            field=models.CharField(blank=True, choices=[('', '---------'), ('1', 'CABALLERO'), ('2', 'DAMA'), ('3', 'JOVEN'), ('4', 'NIÑO/A')], max_length=1, verbose_name='Género'),
        ),
    ]
