# Generated by Django 3.1.7 on 2021-05-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0009_productos_barcodeimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='medida',
            field=models.CharField(blank=True, choices=[('', '---------'), ('00', '21'), ('01', '22'), ('02', '23'), ('03', '24'), ('04', '25'), ('05', '26'), ('06', '27'), ('07', '28'), ('08', '29'), ('09', '30'), ('', '---------'), ('10', '21.5'), ('11', '22.5'), ('12', '23.5'), ('13', '24.5'), ('14', '25.5'), ('15', '26.5'), ('16', '27.5'), ('17', '28.5'), ('18', '29.5')], max_length=2, verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='talla',
            field=models.CharField(blank=True, choices=[('00', 'CH'), ('01', 'M'), ('02', 'G')], max_length=2, verbose_name='Talla'),
        ),
    ]
