# Generated by Django 3.1.7 on 2021-05-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0010_auto_20210514_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='modelo',
            field=models.CharField(blank=True, max_length=3, verbose_name='Modelo'),
        ),
    ]
