# Generated by Django 3.1.7 on 2021-05-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0011_auto_20210514_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(choices=[('00', 'CALZADO'), ('01', 'ROPA')], max_length=2, verbose_name='Tipo de producto'),
        ),
    ]
