# Generated by Django 3.1.7 on 2021-05-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0012_auto_20210514_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='color',
            field=models.CharField(blank=True, choices=[('00', 'ROJO'), ('01', 'AZUL'), ('02', 'AMARILLO'), ('03', 'NEGRO'), ('04', 'MORADO'), ('05', 'VERDE'), ('06', 'BLANCO')], max_length=2, verbose_name='Color'),
        ),
    ]
