# Generated by Django 3.1.7 on 2021-05-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0015_auto_20210514_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, verbose_name='Código de barras'),
        ),
    ]
