# Generated by Django 3.1.7 on 2021-05-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0018_auto_20210514_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='barcodeimg',
        ),
    ]
