# Generated by Django 3.1.7 on 2021-05-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0019_remove_productos_barcodeimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='barcode',
            field=models.CharField(max_length=13, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='color',
            field=models.CharField(blank=True, choices=[('0', 'ROJO'), ('1', 'AZUL'), ('2', 'AMARILLO'), ('3', 'NEGRO'), ('4', 'MORADO'), ('5', 'VERDE'), ('6', 'BLANCO')], max_length=2, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='linea',
            field=models.CharField(blank=True, choices=[('0', 'ADULTO'), ('1', 'NIÑO'), ('2', 'CABALLERO'), ('3', 'DAMA')], max_length=2, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(choices=[('0', 'CALZADO'), ('1', 'ROPA')], max_length=2, verbose_name='Tipo de producto'),
        ),
    ]
