# Generated by Django 3.1.7 on 2021-05-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0022_auto_20210514_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
