# Generated by Django 3.1.7 on 2021-05-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0023_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
