# Generated by Django 3.1.7 on 2021-05-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0024_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='barcode',
            field=models.CharField(blank=True, default=1, max_length=13, verbose_name='Código de barras'),
            preserve_default=False,
        ),
    ]
