# Generated by Django 3.1.7 on 2021-05-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0025_auto_20210514_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Código de barras'),
        ),
    ]
