# Generated by Django 3.1.7 on 2021-05-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0026_auto_20210514_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='almacen',
            field=models.CharField(choices=[('10', 'ALMACEN 1'), ('20', 'ALMACEN 2'), ('30', 'ALMACEN 3')], max_length=2, verbose_name='Almacén'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='barcode',
            field=models.CharField(blank=True, default=0, max_length=13, unique=True, verbose_name='Código de barras'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productos',
            name='color',
            field=models.CharField(blank=True, choices=[('00', 'ROJO'), ('01', 'AZUL'), ('02', 'AMARILLO'), ('03', 'NEGRO'), ('04', 'MORADO'), ('05', 'VERDE'), ('06', 'BLANCO')], max_length=2, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='linea',
            field=models.CharField(blank=True, choices=[('00', 'ADULTO'), ('01', 'NIÑO'), ('02', 'CABALLERO'), ('03', 'DAMA')], max_length=2, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(choices=[('10', 'CALZADO'), ('20', 'ROPA')], max_length=2, verbose_name='Tipo de producto'),
        ),
    ]
