# Generated by Django 3.1.7 on 2021-05-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0028_auto_20210515_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, unique=True, verbose_name='Código de barras'),
        ),
    ]
