# Generated by Django 3.1.7 on 2021-05-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0029_auto_20210515_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Inventario de Productos'},
        ),
    ]
