# Generated by Django 3.1.7 on 2021-05-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0030_auto_20210522_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['-id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Inventario de Productos'},
        ),
    ]
