# Generated by Django 3.1.7 on 2021-05-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0031_auto_20210522_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='linea',
            field=models.CharField(blank=True, choices=[('00', 'ADULTO'), ('01', 'NIÑO')], max_length=2, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='talla',
            field=models.CharField(blank=True, choices=[('', '---------'), ('00', 'CH'), ('01', 'M'), ('02', 'G'), ('', '---------'), ('03', '16'), ('04', '18'), ('05', '28'), ('06', '30'), ('07', '32'), ('08', '34'), ('09', '36'), ('10', '38'), ('11', '40'), ('12', '42'), ('13', '44')], max_length=2, verbose_name='Talla'),
        ),
    ]
