# Generated by Django 3.1.7 on 2021-08-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('01', 'ENERO'), ('02', 'FEBRERO'), ('03', 'MARZO'), ('04', 'ABRIL'), ('05', 'MAYO'), ('06', 'JUNIO'), ('07', 'JULIO'), ('08', 'AGOSTO'), ('09', 'SEPTIEMBRE'), ('10', 'OCTUBRE'), ('11', 'NOVIEMBRE'), ('12', 'DICIEMBRE')], max_length=2, verbose_name='Mes')),
                ('año', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2015'), ('2015', '2014'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4, verbose_name='Año')),
                ('fecha', models.DateField(blank=True, unique=True)),
                ('cargosBancarios', models.FloatField(default=0, verbose_name='Cargos Bancarios')),
                ('comisionTarjetaCredito', models.FloatField(default=0, verbose_name='Comisión de tarjeta de crédito')),
                ('otrosBancos', models.FloatField(default=0, verbose_name='Otros bancos')),
                ('salariosSueldosWeb', models.FloatField(default=0, verbose_name='Salarios y sueldos web')),
                ('sueldosOficina', models.FloatField(default=0, verbose_name='Sueldos oficina')),
                ('sueldosCorporativos', models.FloatField(default=0, verbose_name='Sueldos corporativos')),
                ('comisionesPagadas', models.FloatField(default=0, verbose_name='Comisiones pagadas')),
                ('jubilacion', models.FloatField(default=0, verbose_name='Jubilación')),
                ('utilidades', models.FloatField(default=0, verbose_name='Utilidades')),
                ('costosReclutamiento', models.FloatField(default=0, verbose_name='Costos de reclutamiento')),
                ('imss', models.FloatField(default=0, verbose_name='IMSS')),
                ('rollosImpresora', models.FloatField(default=0, verbose_name='Rollos de impresora')),
                ('tapiceria', models.FloatField(default=0, verbose_name='Tapicería')),
                ('remodelacionOficina', models.FloatField(default=0, verbose_name='Remodelaciones de oficina')),
                ('predial', models.FloatField(default=0, verbose_name='Predial')),
                ('papeleria', models.FloatField(default=0, verbose_name='Papelería')),
                ('intercomunicador', models.FloatField(default=0, verbose_name='Intercomunicador')),
                ('telefonosOficina', models.FloatField(default=0, verbose_name='Telefonos de oficina')),
                ('luz', models.FloatField(default=0, verbose_name='Luz')),
                ('telefono', models.FloatField(default=0, verbose_name='Telefono')),
                ('lentes', models.FloatField(default=0, verbose_name='Lentes')),
                ('fletes', models.FloatField(default=0, verbose_name='Fletes')),
                ('walmart', models.FloatField(default=0, verbose_name='Walmart')),
                ('reparacionesManteminiento', models.FloatField(default=0, verbose_name='Reparaciones y mantenimiento')),
                ('notas', models.FloatField(default=0, verbose_name='Notas')),
                ('agua', models.FloatField(default=0, verbose_name='Agua')),
                ('policia', models.FloatField(default=0, verbose_name='Policía')),
                ('gastosViajes', models.FloatField(default=0, verbose_name='Gastos de viajes')),
                ('amplificadorBocinas', models.FloatField(default=0, verbose_name='Amplificador y bocinas')),
                ('gastosCheques', models.FloatField(default=0, verbose_name='Gastos cheques')),
                ('gastosOficina', models.FloatField(default=0, verbose_name='Gastos oficina')),
                ('fideicomiso', models.FloatField(default=0, verbose_name='Fideicomiso')),
                ('contador', models.FloatField(default=0, verbose_name='Contador')),
                ('cometra', models.FloatField(default=0, verbose_name='Cometra')),
                ('paletas', models.FloatField(default=0, verbose_name='Paletas')),
                ('finiquito', models.FloatField(default=0, verbose_name='Finiquito')),
                ('honorariosConsultores', models.FloatField(default=0, verbose_name='Honorarios de consultores')),
                ('impuestoCDMX', models.FloatField(default=0, verbose_name='Impuesto CDMX')),
                ('chequesAbril', models.FloatField(default=0, verbose_name='Cheques Abril')),
                ('equipoComputo', models.FloatField(default=0, verbose_name='Equipos de computo')),
                ('mantenimientoComputo', models.FloatField(default=0, verbose_name='Mantenimiento computo')),
                ('viaticos', models.FloatField(default=0, verbose_name='Viaticos')),
                ('comidas', models.FloatField(default=0, verbose_name='Comidas y cenas')),
                ('valoracionInmuebles', models.FloatField(default=0, verbose_name='Valoración de Inmuebles')),
                ('imprenta', models.FloatField(default=0, verbose_name='Imprenta')),
                ('comisionRentaLocal', models.FloatField(default=0, verbose_name='Comisión de renta de local')),
                ('impuestos', models.FloatField(default=0, verbose_name='Impuestos')),
                ('gastosTotales', models.FloatField(blank=True, null=True, verbose_name='Gastos Totales')),
            ],
            options={
                'verbose_name': 'Gastos',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
