# Generated by Django 3.1.7 on 2021-08-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='totales_bancarios',
            field=models.FloatField(blank=True, null=True, verbose_name='Gastos bancarios totales'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='totales_generales',
            field=models.FloatField(blank=True, null=True, verbose_name='Gastos generales totales'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='totales_sueldos',
            field=models.FloatField(blank=True, null=True, verbose_name='Sueldos totales'),
        ),
    ]
