# Generated by Django 3.1.7 on 2021-05-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='type_invoice',
            field=models.CharField(choices=[('1', 'FACTURA'), ('2', 'SIN COMPROBANTE')], max_length=2, verbose_name='TIPO'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='type_payment',
            field=models.CharField(choices=[('0', 'TARJETA'), ('1', 'EFECTIVO'), ('2', 'BONO')], max_length=2, verbose_name='TIPO PAGO'),
        ),
    ]
