# Generated by Django 3.1.7 on 2021-07-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='price_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Subtotal'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='price_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Compra'),
        ),
    ]
