# Generated by Django 3.1.7 on 2021-08-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20210714_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total de Descuento'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='promocion',
            field=models.CharField(blank=True, max_length=2, verbose_name='Promoción de la venta'),
        ),
    ]
