# Generated by Django 3.1.7 on 2021-05-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20210516_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='type_invoice',
            field=models.CharField(choices=[('2', 'Sin Factura'), ('1', 'Factura')], max_length=2, verbose_name='TIPO'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='type_payment',
            field=models.CharField(choices=[('1', 'Efectivo'), ('0', 'Tarjeta')], max_length=2, verbose_name='TIPO PAGO'),
        ),
    ]
