# Generated by Django 3.1.7 on 2021-08-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20210823_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='close',
            field=models.BooleanField(default=False, verbose_name='Venta Cerrada en Caja'),
        ),
    ]
