# Generated by Django 3.1.7 on 2021-05-27 02:50

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20210522_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Efectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Cambio de efectivo',
                'verbose_name_plural': 'Cambio de efectivo',
                'ordering': ['-created'],
            },
        ),
    ]
