from django.urls import path
from . import views

app_name = "ventas_app"

urlpatterns = [
    path(
        'venta/index/',
        views.AddCarView.as_view(),
        name='venta-index',
        ),
    path(
        'carshop/update/<pk>/', 
        views.CarShopUpdateView.as_view(),
        name='carshop-update',
    ),
    path(
        'carshop/update2/<pk>/', 
        views.CarShopUpdate2View.as_view(),
        name='carshop-update2',
    ),
    path(
        'carshop/delete/<pk>/', 
        views.CarShopDeleteView.as_view(),
        name='carshop-delete',
    ),
    path(
        'carshop/delete-all/', 
        views.CarShopDeleteAll.as_view(),
        name='carshop-delete_all',
    ),
    path(
        'venta/simple/', 
        views.ProcesoVentaSimpleView.as_view(),
        name='venta-simple',
    ),
    path(
        'venta/voucher/', 
        views.ProcesoVentaVoucherView.as_view(),
        name='venta-voucher',
    ),
    path(
        'venta/voucher-pdf/<pk>/', 
        views.VentaVoucherPdf.as_view(),
        name='venta-voucher_pdf',
    ),
    path(
        'venta/ultimas-ventas/', 
        views.SaleListView.as_view(),
        name='venta-list',
    ),
    path(
        'venta/delete/<pk>/', 
        views.SaleDeleteView.as_view(),
        name='venta-delete',
    ),
    path(
        'efectivo/', 
        views.EfectivoView.as_view(),
        name='efectivo',
    ),
    path(
        'efectivo/delete-all',
        views.EfectivoDeleteAll.as_view(),
        name='efectivo-delete_all',
    ),
    path(
        'promociones/',
        views.Promociones.as_view(),
        name='promociones',
    ),
    path(
        'promociones/activas/',
        views.ListaPromociones.as_view(),
        name='promociones_activas',
    ),
    path(
        'promocion/familiar/',
        views.PromocionFamiliar.as_view(),
        name='promocion_familiar',
    ),
    path(
        'promociones/eliminar/<pk>',
        views.EliminaPromociones.as_view(),
        name='promociones_eliminar',
    ),
]